# Data types
In this notebook, I am talking about the pincipal types of data in R language, the sintaxis and operations.
## Serching for help
First step is know how can we get help. In this section you will learn the main tools for get help. The first tool which you can use to get help is "help.start()". With this you will find a menu fo resources such as manuals, referrences and other material to start to learn R. R has a system for help to get information about the functions and package installed. To get information about a function, for example, the "print()" function you can write "?print" in the command line.

In [4]:
?print

print                   package:base                   R Documentation

_P_r_i_n_t _V_a_l_u_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'print' prints its argument and returns it _invisibly_ (via
     'invisible(x)').  It is a generic function which means that new
     printing methods can be easily added for new 'class'es.

_U_s_a_g_e:

     print(x, ...)
     
     ## S3 method for class 'factor'
     print(x, quote = FALSE, max.levels = NULL,
           width = getOption("width"), ...)
     
     ## S3 method for class 'table'
     print(x, digits = getOption("digits"), quote = FALSE,
           na.print = "", zero.print = "0",
           right = is.numeric(x) || is.complex(x),
           justify = "none", ...)
     
     ## S3 method for class 'function'
     print(x, useSource = TRUE, ...)
     
_A_r_g_u_m_e_n_t_s:

       x: an object used to select a method.

     ...: further arguments passed to or from other methods.

   quote: logical, indicating whether or not strings should be printed
          with surrounding quotes.

max.levels: integer, indicating how many levels should be printed for a
          factor; if '0', no extra "Levels" line will be printed.  The
          default, 'NULL', entails choosing 'max.levels' such that the
          levels print on one line of width 'width'.

   width: only used when 'max.levels' is NULL, see above.

  digits: minimal number of _significant_ digits, see 'print.default'.

na.print: character string (or 'NULL') indicating 'NA' values in
          printed output, see 'print.default'.

zero.print: character specifying how zeros ('0') should be printed; for
          sparse tables, using '"."' can produce more readable results,
          similar to printing sparse matrices in 'Matrix'.

   right: logical, indicating whether or not strings should be right
          aligned.

 justify: character indicating if strings should left- or
          right-justified or left alone, passed to 'format'.

useSource: logical indicating if internally stored source should be
          used for printing when present, e.g., if 'options(keep.source
          = TRUE)' has been in use.

_D_e_t_a_i_l_s:

     The default method, 'print.default' has its own help page.  Use
     'methods("print")' to get all the methods for the 'print' generic.

     'print.factor' allows some customization and is used for printing
     'ordered' factors as well.

     'print.table' for printing 'table's allows other customization. As
     of R 3.0.0, it only prints a description in case of a table with
     0-extents (this can happen if a classifier has no valid data).

     See 'noquote' as an example of a class whose main purpose is a
     specific 'print' method.

_R_e_f_e_r_e_n_c_e_s:

     Chambers, J. M. and Hastie, T. J. (1992) _Statistical Models in
     S._ Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     The default method 'print.default', and help for the methods
     above; further 'options', 'noquote'.

     For more customizable (but cumbersome) printing, see 'cat',
     'format' or also 'write'.  For a simple prototypical print method,
     see '.print.via.format' in package 'tools'.

_E_x_a_m_p_l_e_s:

     require(stats)
     
     ts(1:20)  #-- print is the "Default function" --> print.ts(.) is called
     for(i in 1:3) print(1:i)
     
     ## Printing of factors
     attenu$station ## 117 levels -> 'max.levels' depending on width
     
     ## ordered factors: levels  "l1 < l2 < .."
     esoph$agegp[1:12]
     esoph$alcgp[1:12]
     
     ## Printing of sparse (contingency) tables
     set.seed(521)
     t1 <- round(abs(rt(200, df = 1.8)))
     t2 <- round(abs(rt(200, df = 1.4)))
     table(t1, t2) # simple
     print(table(t1, t2), zero.print = ".") # nicer to read
     
     ## same for non-integer "table":
     T <- table(t2,t1)
     T <- T * (1+round(rlnorm(length(T)))/4)
     print(T, zero.print = ".") # quite nicer,
     print.table(T[,

As you can see, ? symbol show you a brief description of the function, its arguments, etc. In the same order you can use help() function, it is equivalent to ?. When you use help() you need pass the name of the function with "", for example help("print").

In [5]:
help("print")

print                   package:base                   R Documentation

_P_r_i_n_t _V_a_l_u_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'print' prints its argument and returns it _invisibly_ (via
     'invisible(x)').  It is a generic function which means that new
     printing methods can be easily added for new 'class'es.

_U_s_a_g_e:

     print(x, ...)
     
     ## S3 method for class 'factor'
     print(x, quote = FALSE, max.levels = NULL,
           width = getOption("width"), ...)
     
     ## S3 method for class 'table'
     print(x, digits = getOption("digits"), quote = FALSE,
           na.print = "", zero.print = "0",
           right = is.numeric(x) || is.complex(x),
           justify = "none", ...)
     
     ## S3 method for class 'function'
     print(x, useSource = TRUE, ...)
     
_A_r_g_u_m_e_n_t_s:

       x: an object used to select a method.

     ...: further arguments passed to or from other methods.

   quote: logical, indicating whether or not strings should be printed
          with surrounding quotes.

max.levels: integer, indicating how many levels should be printed for a
          factor; if '0', no extra "Levels" line will be printed.  The
          default, 'NULL', entails choosing 'max.levels' such that the
          levels print on one line of width 'width'.

   width: only used when 'max.levels' is NULL, see above.

  digits: minimal number of _significant_ digits, see 'print.default'.

na.print: character string (or 'NULL') indicating 'NA' values in
          printed output, see 'print.default'.

zero.print: character specifying how zeros ('0') should be printed; for
          sparse tables, using '"."' can produce more readable results,
          similar to printing sparse matrices in 'Matrix'.

   right: logical, indicating whether or not strings should be right
          aligned.

 justify: character indicating if strings should left- or
          right-justified or left alone, passed to 'format'.

useSource: logical indicating if internally stored source should be
          used for printing when present, e.g., if 'options(keep.source
          = TRUE)' has been in use.

_D_e_t_a_i_l_s:

     The default method, 'print.default' has its own help page.  Use
     'methods("print")' to get all the methods for the 'print' generic.

     'print.factor' allows some customization and is used for printing
     'ordered' factors as well.

     'print.table' for printing 'table's allows other customization. As
     of R 3.0.0, it only prints a description in case of a table with
     0-extents (this can happen if a classifier has no valid data).

     See 'noquote' as an example of a class whose main purpose is a
     specific 'print' method.

_R_e_f_e_r_e_n_c_e_s:

     Chambers, J. M. and Hastie, T. J. (1992) _Statistical Models in
     S._ Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     The default method 'print.default', and help for the methods
     above; further 'options', 'noquote'.

     For more customizable (but cumbersome) printing, see 'cat',
     'format' or also 'write'.  For a simple prototypical print method,
     see '.print.via.format' in package 'tools'.

_E_x_a_m_p_l_e_s:

     require(stats)
     
     ts(1:20)  #-- print is the "Default function" --> print.ts(.) is called
     for(i in 1:3) print(1:i)
     
     ## Printing of factors
     attenu$station ## 117 levels -> 'max.levels' depending on width
     
     ## ordered factors: levels  "l1 < l2 < .."
     esoph$agegp[1:12]
     esoph$alcgp[1:12]
     
     ## Printing of sparse (contingency) tables
     set.seed(521)
     t1 <- round(abs(rt(200, df = 1.8)))
     t2 <- round(abs(rt(200, df = 1.4)))
     table(t1, t2) # simple
     print(table(t1, t2), zero.print = ".") # nicer to read
     
     ## same for non-integer "table":
     T <- table(t2,t1)
     T <- T * (1+round(rlnorm(length(T)))/4)
     print(T, zero.print = ".") # quite nicer,
     print.table(T[,

If you need information of operator like +, -, * They are in inverse quotation marks. For example, for information of +, you need digit help(\`+\`) or ?\` + \` in command line. Other tool avaible is apropos() function. It need a string in quotation marks as argument and it shows you a list of all function wich cointain this string.

In [6]:
apropos("class")

[1] ".checkMFClasses"           ".classEnv"                
 [3] ".MFclass"                  ".OldClassesList"          
 [5] ".selectSuperClasses"       ".valueClassTest"          
 [7] "all.equal.envRefClass"     "assignClassDef"           
 [9] "class"                     "class<-"                  
[11] "classesToAM"               "classLabel"               
[13] "classMetaName"             "className"                
[15] "completeClassDefinition"   "completeSubclasses"       
[17] "data.class"                "findClass"                
[19] "getAllSuperClasses"        "getClass"                 
[21] "getClassDef"               "getClasses"               
[23] "getClassName"              "getClassPackage"          
[25] "getRefClass"               "getSubclasses"            
[27] "insertClassMethods"        "isClass"                  
[29] "isClassDef"                "isClassUnion"             
[31] "isSealedClass"             "isVirtualClass"           
[33] "isXS3Class"                "makeClassRepresentation"  
[35] "makePrototypeFromClassDef" "multipleClasses"          
[37] "namespaceImportClasses"    "nclass.FD"                
[39] "nclass.scott"              "nclass.Sturges"           
[41] "newClassRepresentation"    "oldClass"                 
[43] "oldClass<-"                "promptClass"              
[45] "removeClass"               "resetClass"               
[47] "S3Class"                   "S3Class<-"                
[49] "sealClass"                 "selectSuperClasses"       
[51] "setClass"                  "setClassUnion"            
[53] "setOldClass"               "setRefClass"              
[55] "showClass"                 "superClassDepth"          
[57] "unclass"

You can use example() function for example("read.table"). R can show information about a command, for example ??regression. It is equivalent a help.search("regression"). Other form to get help is library function with help argument. Some package has vignette, it is a short documment with instructions to use their functions.

In [10]:
library(help = "stats")

Documentation for package 'stats'


		Information on package 'stats'

Description:

Package:            stats
Version:            3.6.1
Priority:           base
Title:              The R Stats Package
Author:             R Core Team and contributors worldwide
Maintainer:         R Core Team <R-core@r-project.org>
Description:        R statistical functions.
License:            Part of R 3.6.1
Imports:            utils, grDevices, graphics
Suggests:           MASS, Matrix, SuppDists, methods, stats4
NeedsCompilation:   yes
Built:              R 3.6.1; x86_64-w64-mingw32; 2019-10-03 18:01:05
                    UTC; windows

Index:

.checkMFClasses         Functions to Check the Type of Variables passed
                        to Model Frames
AIC                     Akaike's An Information Criterion
ARMAacf                 Compute Theoretical ACF for an ARMA Process
ARMAtoMA                Convert ARMA Process to Infinite MA Process
Beta                    The Beta Distribution
Binomial 

In [13]:
vignette()

Vignettes in package 'digest':

sha1                    sha1() versus digest() (source, html)
Vignettes in package 'grid':

moveline                Demonstrating move-to and line-to (source, pdf)
displaylist             Display Lists in grid (source, pdf)
interactive             Editing grid Graphics (source, pdf)
frame                   Frames and packing grobs (source, pdf)
grid                    Introduction to grid (source, pdf)
locndimn                Locations versus Dimensions (source, pdf)
sharing                 Modifying multiple grobs simultaneously
                        (source, pdf)
nonfinite               Non-finite values (source, pdf)
saveload                Persistent representations (source, pdf)
rotated                 Rotated Viewports (source, pdf)
grobs                   Working with grid grobs (source, pdf)
viewports               Working with viewports (source, pdf)
plotexample             Writing grid Code (source, pdf)
Vignettes in package 'jsonlite':

json-mapping            A mapping between JSON data and R objects
                        (source, pdf)
json-paging             Combining pages of JSON data with jsonlite
                        (source, html)
json-apis               Fetching JSON data from REST APIs (source,
                        html)
json-aaquickstart       Getting started with JSON and jsonlite (source,
                        html)
json-opencpu            Simple JSON RPC with OpenCPU (source, pdf)
Vignettes in package 'parallel':

parallel                Package 'parallel' (source, pdf)
Vignettes in package 'pbdZMQ':

pbdZMQ-guide            pbdZMQ-guide (source, pdf)
Vignettes in package 'Rcpp':

Rcpp-attributes         Rcpp-attributes (source, pdf)
Rcpp-extending          Rcpp-extending (source, pdf)
Rcpp-FAQ                Rcpp-FAQ (source, pdf)
Rcpp-introduction       Rcpp-introduction (source, pdf)
Rcpp-jss-2011           Rcpp-JSS-2011 (source, pdf)
Rcpp-modules            Rcpp-modules (source, pdf)
Rcpp-package            Rcpp-package (source, pdf)
Rcpp-quickref           Rcpp-quickref (source, pdf)
Rcpp-sugar              Rcpp-sugar (source, pdf)
Vignettes in package 'utils':

Sweave                  Sweave User Manual (source, pdf)

## Types of data and basical opetations
In this section we learning about the types of data and different operations in R language. When you introduce an expression in command line, R resolves it and show you the reuslt if it is possible. R can make mathematical and logical operations.

In [35]:
print(3+7) # You can do mathematical operations
my_variable <- (180 / 6) - 15 # The <- symbol is used to asign value to variable
print(my_variable)
(180 / 60) - 15 -> my_variable_2 # Ypu can assign from left to right
print(my_variable_2) # Note that, when we print the answer has [1] it is because the answer is a vector
y <- c(561, 1105, 1729, 2465, 2821) # c instruction is to create a vector with many values
print(y)
print(1:100) # You can make vector which use more than one line, ":" symbol is usefull to do it
print(c(1.1, 2.2, 3.3, 4.4) - c(1, 1, 1, 1)) # The operation with vectors are element by element 
print(c(1, 2, 3, 4, 5, 6, 7, 8) - c(1, 2)) # If the vectors have different length, the smallest will be repeat necesary time
ls() # ls function list all variables in memory
print("Hello Word!")
colors <- c("red", "blue", "green", "blue", "red")
print(colors) # Vector with string values
print(class(3)) # Numeric class
print(class(5+7i)) # Complex class
print(class(T)) # Logical class
print(T&F) # Logical operations
print(my_variable == 15) # Logical comparations
length(my_variable_2) <- 3
print(my_variable_2) # NA is special value which means Not Avaible
print(2^1024) # INF is special value for too high values
print(0/0) # NaN value which means Not is a Number

[1] 10
[1] 15
[1] -12
[1]  561 1105 1729 2465 2821
  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100
[1] 0.1 1.2 2.3 3.4
[1] 0 0 2 2 4 4 6 6


[1] "colors"        "my_variable"   "my_variable_2" "y"

[1] "Hello Word!"
[1] "red"   "blue"  "green" "blue"  "red"  
[1] "numeric"
[1] "complex"
[1] "logical"
[1] FALSE
[1] TRUE
[1] -12  NA  NA
[1] Inf
[1] NaN


## Date manipulation
R has some classes to manipulate date: Date, POSIXct, POSIXlt. For example, to get the date of today whe can use Sys.Date()

In [42]:
print(Sys.Date()) # Print date of today
print(vector("numeric", length = 10)) # vector function is usefull. It need type and length
print(vector("character", length = 10)) # vector with character values
print(vector("logical", length = 10)) # vector with logical values
# Vector can only have the same type of data. List can have different values of different data
print(list(0, "Hello", T))
print(c(T, 19, 1+3i)) # R convert al values to the same type.
c <- vector("numeric", length = 5)
print(as.logical(c)) # This convert all values to logical type, you can use as.numeric, as.character, as.integer

[1] "2022-05-22"
 [1] 0 0 0 0 0 0 0 0 0 0
 [1] "" "" "" "" "" "" "" "" "" ""
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[[1]]
[1] 0

[[2]]
[1] "Hello"

[[3]]
[1] TRUE

[1]  1+0i 19+0i  1+3i
[1] FALSE FALSE FALSE FALSE FALSE


## Matrix
Matrix are like vector in two dimensions. To create it we can use matrix function (data and dimension), rbind (create with vector as rows), cbind (create with vector as columns) and as.matrix() (to cast to matrix). 
Factores are otthe special type of categorical data. 
Dataframe are other special type of data, with two dimension of labeled data. Each column can have different type of data.

In [51]:
print(matrix(data = 1:12, nrow = 4, ncol = 3)) # Create matrix with matrix function
print(rbind(y, y)) # Create matrix with rbind function
print(cbind(y,y)) # Create matrix with cbind function
print(factor(colors)) # Factors presents without quation marks an leves are show explicitly
print(data.frame(keys = y, color = colors)) # You can use read.table or read.csv functions
print(data.matrix(data.frame(keys = y, color = colors))) # You can use data.matrix to make dataframe in matrix

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
  [,1] [,2] [,3] [,4] [,5]
y  561 1105 1729 2465 2821
y  561 1105 1729 2465 2821
        y    y
[1,]  561  561
[2,] 1105 1105
[3,] 1729 1729
[4,] 2465 2465
[5,] 2821 2821
[1] red   blue  green blue  red  
Levels: blue green red
  keys color
1  561   red
2 1105  blue
3 1729 green
4 2465  blue
5 2821   red
     keys color
[1,]  561     3
[2,] 1105     1
[3,] 1729     2
[4,] 2465     1
[5,] 2821     3


## Substructures
In this section, we will learn how we can access to data structure in R. [] is used to access values in vector or matrix.

In [78]:
my_vector <- 11:30
print(my_vector)
print(my_vector[1]) # Access to first element in vector
print(my_vector[3:8]) # Access elemento from 3 to 8
print(my_vector[c(4, 6, 13)]) # We can access with indexes as vector
print(my_vector[c(6, 13, 4)]) # The indexes are not necessary in order
print(my_vector[-9:-15]) # You can use - symbol to exlude elements in the selection
print(my_vector[rep(c(T, F), 10)]) # You can use boolean vector to access values
print(my_vector[c(F, F, T)]) # For logical vector, it will repeat if the length are not suficient
print(my_vector[my_vector > 20]) # You can use bodcast to get elements
my_array <- array(1:18,dim=c(3,3,2)) # You can create a multidimensional array
print(my_array)
print(my_array[2, 2, 1]) # You can access with each dimension separate by comma
print(my_array[1:2, 1:2, 1]) # You can access multidimensional
my_matrix <- array(1:9, dim = c(3,3)) # Create a matrix as array with two dimensions
print(my_matrix)
print(my_matrix[1,]) # Omit values it mean all columns
print(my_matrix[c(1,3),]) # You can use different values in vector 

 [1] 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
[1] 11
[1] 13 14 15 16 17 18
[1] 14 16 23
[1] 16 23 14
 [1] 11 12 13 14 15 16 17 18 26 27 28 29 30
 [1] 11 13 15 17 19 21 23 25 27 29
[1] 13 16 19 22 25 28
 [1] 21 22 23 24 25 26 27 28 29 30
, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

[1] 5
     [,1] [,2]
[1,]    1    4
[2,]    2    5
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 1 4 7
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    3    6    9


In [91]:
# In list, each element have names
car <- list(color = "red", tires = 4, mark = "Renault", cylinders = 4)
print(car)
print(car$color) # You can use $ symbol to gt values with number
print(car[c("tires", "cylinders")]) #You can use names in vector
print(car[["mark"]]) # You can use name in doble []
print(car[["ma", exact = F]]) # You can use incomplete name
print(cars)
print(cars$speed)
print(cars$speed[cars$dist > 100]) # Print values with broadcast

$color
[1] "red"

$tires
[1] 4

$mark
[1] "Renault"

$cylinders
[1] 4

[1] "red"
$tires
[1] 4

$cylinders
[1] 4

[1] "Renault"
[1] "Renault"
   speed dist
1      4    2
2      4   10
3      7    4
4      7   22
5      8   16
6      9   10
7     10   18
8     10   26
9     10   34
10    11   17
11    11   28
12    12   14
13    12   20
14    12   24
15    12   28
16    13   26
17    13   34
18    13   34
19    13   46
20    14   26
21    14   36
22    14   60
23    14   80
24    15   20
25    15   26
26    15   54
27    16   32
28    16   40
29    17   32
30    17   40
31    17   50
32    18   42
33    18   56
34    18   76
35    18   84
36    19   36
37    19   46
38    19   68
39    20   32
40    20   48
41    20   52
42    20   56
43    20   64
44    22   66
45    23   54
46    24   70
47    24   92
48    24   93
49    24  120
50    25   85
 [1]  4  4  7  7  8  9 10 10 10 11 11 12 12 12 12 13 13 13 13 14 14 14 14 15 15
[26] 15 16 16 17 17 17 18 18 18 18 19 19 19 20 20 20 20 20 22 23 

## Write and read data
In this section we will learn about how we can load data and save it. In R we can add several information of others programs, you can only need url or path of file. In general, the most common format is csv. The principal function are read.table(), read.csv(), read.delim(). read.csv2() or read.delim2() if in your region use commas to separte decimals.

In [11]:
data <- read.table("data/inmigintnalpry.csv", header=TRUE, sep=",", fileEncoding = "latin1") # Read csv file
data2 <- read.table("data/inmigintnalpry.csv", header=TRUE, sep=",") # fileEnconding in latin1 is usefull to iondentify correctly words like año
first100 <- read.table("data/inmigintnalpry.csv", header=TRUE, sep=",", fileEncoding = "latin1", nrow = 100)
# You can read only 100 first rows
classes <- sapply(first100, class) # Sapply apply class function each column in first100

In [15]:
data <- read.table("data/inmigintnalpry.csv", header=TRUE, sep=",", fileEncoding = "latin1", colClasses=classes)
#With this we can read more efficient

In [17]:
save(data, classes, file="data/datos_inmigrates.RData") # Save variables

In [19]:
rm(data,classes) # Remove varibles of workspace

In [20]:
ls() # We can check if its works with ls() command

[1] "data2"    "datas2"   "datos2"   "first100"

In [21]:
load("data/datos_inmigrates.RData") # You can load that variables and check it
ls() # All data in R can access in different opearating sistem
# save.image() is for save all variables in workspace

[1] "classes"  "data"     "data2"    "datas2"   "datos2"   "first100"

In [22]:
write.csv(data, "data/export_data.csv") # Write data in csv file

## Functions
In this section I show you sereval forms to write functions in R.

In [26]:
add <- function(a, b){ # Write functions with arguments
    a + b # FUnction return last value evaluated
}
add(3, 4)

[1] 7

In [28]:
add # You can see the code of function only writing its name. 

function(a, b){
    a + b
}

In [48]:
mul <- function(a, y = 1){ # You can assign a previus value in declaration
    a * y
}
print(mul(4))
print(mul(4, 2))
add_mul <- function(a = 0, b = 0, ...){ # ... is usefull to design more arguments
    a + b + ...
}
print(add_mul(1,2,5))
print(args(add_mul)) # args is function to see the args of function
print(formals(add_mul)) # it's more formal to see arguments 
fun_cuad <- function(a, b, fun){ # You can pass function as argument
    (fun(a, b))^2
}
print(fun_cuad(2, 4, add)) # Add function to square
print(fun_cuad(2, 4, mul)) # mul function to square

[1] 4
[1] 8
[1] 8
function (a = 0, b = 0, ...) 
NULL
$a
[1] 0

$b
[1] 0

$...


[1] 36
[1] 64


## Apply function
In this section you will be learn about apply(). The function apply() needs 3 arguments, vector or matrix X, margin 1: if the function apply to rows and 2: if the funtion apply to columns. And fun, that is the function to apply.

In [57]:
my_matrix <- matrix(data = 1:16, nrow = 4, ncol = 4)
print(apply(my_matrix, 2, min))  # Aplication of apply
my_list <- list("Introduction", "to", "the", "Stadistical", "Programmation", "with", "R")
print(lapply(my_list, toupper)) # lapply is usefull is for lists
asa_data <- read.csv("data/ASA_estadisticasPasajeros.csv") 
print(lapply(asa_data, class)) # Ypu can use lapply in dataframe
print(unique(asa_data$Descripcion)) # You can see unique values with unique() function

[1]  1  5  9 13
[[1]]
[1] "INTRODUCTION"

[[2]]
[1] "TO"

[[3]]
[1] "THE"

[[4]]
[1] "STADISTICAL"

[[5]]
[1] "PROGRAMMATION"

[[6]]
[1] "WITH"

[[7]]
[1] "R"

$Anio.mes
[1] "integer"

$Codigo.IATA
[1] "factor"

$Descripcion
[1] "factor"

$Estado
[1] "factor"

$Pasajeros.nacionales
[1] "integer"

$Pasajeros.internacionales
[1] "integer"

 [1] Ciudad Obregon    Colima            Ciudad del Carmen Campeche         
 [5] Chetumal          Ciudad Victoria   Guaymas           Loreto           
 [9] Matamoros         Nuevo Laredo      Nogales           Poza Rica        
[13] Puebla            Puerto Escondido  Tehuacan          Tepic            
[17] Tamuin            Uruapan          
18 Levels: Campeche Chetumal Ciudad del Carmen ... Uruapan


In [63]:
asa_passengers <- asa_data[,c("Pasajeros.nacionales", "Pasajeros.internacionales")] # Select only two columns
print(lapply(asa_passengers, sum)) # Get sum of two columns
print(table(asa_data$Estado)) # Print values of State
print(tapply(asa_data$Pasajeros.nacionales, asa_data$Estado, sum)) # tapply calcute data with agruppation, first
# is vecto, second is indexes, and last is function to apply.

$Pasajeros.nacionales
[1] 2291419

$Pasajeros.internacionales
[1] 176741


Baja California  Sur             Campeche               Colima 
                  12                   24                   12 
           Michoacan              Nayarit               Oaxaca 
                  12                   12                   12 
              Puebla         Quintana Roo      San Luis Potosi 
                  24                   12                   12 
              Sonora           Tamaulipas             Veracruz 
                  36                   36                   12 
Baja California  Sur             Campeche               Colima 
               12602               769864               112656 
           Michoacan              Nayarit               Oaxaca 
               95635               113043               181706 
              Puebla         Quintana Roo      San Luis Potosi 
              267567               179259                 1598 
              Sonora         